version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - LLM_TIMEOUT=15
      - DEFAULT_TENANT=default
    depends_on:
      - db
      - redis
    volumes:
      - ./uploads:/app/uploads

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  flowise:
    image: flowiseai/flowise:latest
    ports:
      - "3001:3000"
    environment:
      - FLOWISE_USERNAME=admin
      - FLOWISE_PASSWORD=admin123
      - DATABASE_TYPE=sqlite
      - DATABASE_PATH=/home/node/.flowise
      - APIKEY_PATH=/home/node/.flowise
      - LOG_PATH=/home/node/.flowise/logs
      - LOG_LEVEL=info
      - EXECUTION_MODE=local
      - TOOL_FUNCTION_TIME_LIMIT=60000
      - FLOWISE_PORT=3000
    volumes:
      - flowise_data:/home/node/.flowise
    depends_on:
      - redis

volumes:
  mysql_data:
  redis_data:
  flowise_data:
